### ISSUE TITLE
using slooh expolrer

### ISSUE THREAD

**Issue by Porygon-2** [Calteo/Slooh.Explorer#3]
Hi I heard that slooh explorer makes it easier to download images and fits from our missions so I installed it. I am having issues with using this software, how to download fits data for a specific object? also does it download all available mission data for that object?

Thanks for helping

**Comment by Calteo** [comment]
Hello,
in the main view the column FITS gets checked if there are FITS image available. You have to check the wanted options before "Information" / "Pictures" / "JPEG" or "FITS". Only then these elements get downloaded.
Information will save an XML file containing data about this mission so other progamms can read it.

To download just certain missions you can (multi-)select (Shift-Click or Ctrl-click) on the mission list and then "Download". Only the selected missions get downloaded.

I hope this helps. If not keep asking.

**Comment by Porygon-2** [comment]
> Hello, in the main view the column FITS gets checked if there are FITS image available. You have to check the wanted options before "Information" / "Pictures" / "JPEG" or "FITS". Only then these elements get downloaded. Information will save an XML file containing data about this mission so other progamms can read it.
> 
> To download just certain missions you can (multi-)select (Shift-Click or Ctrl-click) on the mission list and then "Download". Only the selected missions get downloaded.
> 
> I hope this helps. If not keep asking.

Thanks! that worked out
