### ISSUE TITLE
Slooh Explorer Loading All Observations - Limit to Date 

### ISSUE THREAD

**Issue by erikw1234** [Calteo/Slooh.Explorer#4]
Hi,

Thanks for creating Slooh Explorer, I find it very helpful.

Each time I start Slooh Explorer, it loads all of my observations, and that amounts to 10 years of observations for me. It takes about 30 minutes to load all of the observations, during which time, Slooh Explorer is completely unresponsive. Once it has finished loading all observations, it becomes responsive again, and I can use it to download my observations.

As an enhancement, on the login screen, can you include a date field that defaults to 14 days in the past. Then use that date to filter observations so that Slooh Explorer doesn't reload all 10 years (in my case) of observations. This feature will make SE much faster to work with since I wouldn't have to wait for the 30 minutes for it to load observations. Also include a checkmark for All dates, in which case you disable the date control and load all observations as you normally do.

Thanks for your consideration,
Erik

**Comment by Calteo** [comment]
Hello Erik,

that sounds like a good idea to have a time limit or maybe a limit on the number of observations. 
I will see when I get around to add this feature.

Clear skies,
Matthias

**Comment by Calteo** [comment]
### Changes
I added an exta line of input fields above the grid.

- Start gives the start number of the mission/capture
- Limit give the amount of elements to fetch
- The checkboxes activate the search for missions and/or captures (= pictures not take though missions)

Using the fetsch button the search can be started with differnt parameters.

### Limitations
- Unforturnately there is not an API to query by date, but fortunately for now the missions/captures come in newest first order. So fetching the first 20 missions will alway get the newest ones.
- The query for the captures is quite slow by itself so this alway take a longer time to return some value. But you can deactivate that search if not needed.

**Comment by erikw1234** [comment]
Oh wow, this is great! So much faster!

Thank you -Erik
