### ISSUE TITLE
Error in the app

### ISSUE THREAD

**Issue by Bogdanel23** [Calteo/Slooh.Explorer#5]
![SloohExplorer_issue1](https://github.com/Calteo/Slooh.Explorer/assets/164760254/cfd950d6-fffb-404f-9f83-4465ae5f0b4e)
![SloohExplorer_issue2](https://github.com/Calteo/Slooh.Explorer/assets/164760254/fc774061-db8e-473e-8a62-90030c19c1ce)

Hi,

First of all i want to thank you for creating this tool, made my life a lot easier since i do a lot of mission with Slooh.
I used it in the last 2-3 years with no change of version or any kind of issues. However, it's already 1 week now since i have some error messages popping up and also a change in the interface.
First issue is that after opening the app, the rows with the location to store the downloads is empty and i have to select it each time. Also, the rows with the format for the folder output are also empty (Mission, Information, Pictures, JPEG and FITS) I wasn't inspired to to a screenshot at the time when this had the formula inside.
Second issue is that i always get the error that the access to the provided path is denied. I tried many locations and i get the same error. I also updated the app to the newest version with no success, same errors appear.
It sucks that i cannot use it because it's a game changer.

Can you help me?

Many thanks!
Bogdan

**Comment by Calteo** [comment]
- Have you tried to select a folder using the "Select" button?
- Does the target folder exist?
- Do you have normal access to it though the file explorer?
- I would be interesting to see the stack trace in full. Can you copy it as text into the comments?
- The user settings are saved at C:\Users\<UserId>\AppData\Roaming\Slooh. Can you check if an xml file Slooh.Explorer.SloohUserSetting.xml is saved there. The filenames you type in should saved there when the programm is closed _normally_.
- Is the programm really running in your user account? (Can be found in the details of the task manager. Some of the error seem as if the programm is running as a differnent user.

The layout has been changed to limit the amount of mission fetched initially. Some people with a large number of missions faced a very long startup time until *all* missions had been loaded. Now only the first few a fetched and you can select a large number if you want to.

**Comment by Bogdanel23** [comment]
The error message in full:

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Users\Bogdan\Desktop\Slooh downloader 2' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Slooh.Explorer.Picture.SaveStream(String filename)
   at Slooh.Explorer.Controls.DashboardControl.Download(String missionFolder, Picture picture, String pattern, Boolean overwrite, String extension, Action`2 saveToAction, Action`2 saveAction)
   at Slooh.Explorer.Controls.DashboardControl.Download(Mission mission, InformationFormatter formatter)
   at Slooh.Explorer.Controls.DashboardControl.<>c__DisplayClass59_1.<ButtonDownloadClick>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Slooh.Explorer.Controls.DashboardControl.Work(Func`3 createTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Private.CoreLib.dll
----------------------------------------
Slooh.Explorer
    Assembly Version: 1.1.40.0
    Win32 Version: 1.1.40.0
    CodeBase: file:///C:/Users/Bogdan/Desktop/Bogdan/9.%20Astrofotografie/SLOOH/Slooh-Explorer-Binary-1.1.40/output/Slooh.Explorer.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.722.32203
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.7/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.722.32203
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.7/System.Windows.Forms.Primitives.dll
----------------------------------------
Toolbox.CommandLine
    Assembly Version: 1.0.31.0
    Win32 Version: 1.0.31
    CodeBase: file:///C:/Users/Bogdan/Desktop/Bogdan/9.%20Astrofotografie/SLOOH/Slooh-Explorer-Binary-1.1.40/output/Toolbox.CommandLine.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/netstandard.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.7/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Collections.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Drawing.Primitives.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Linq.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Collections.Specialized.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.722.32203
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.7/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.ComponentModel.TypeConverter.dll
----------------------------------------
Toolbox.Help.WinForms
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5
    CodeBase: file:///C:/Users/Bogdan/Desktop/Bogdan/9.%20Astrofotografie/SLOOH/Slooh-Explorer-Binary-1.1.40/output/Toolbox.Help.WinForms.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.ComponentModel.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Numerics.Vectors.dll
----------------------------------------
Toolbox.Core
    Assembly Version: 0.2.6.0
    Win32 Version: 0.2.6
    CodeBase: file:///C:/Users/Bogdan/Desktop/Bogdan/9.%20Astrofotografie/SLOOH/Slooh-Explorer-Binary-1.1.40/output/Toolbox.Core.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.ObjectModel.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Runtime.Loader.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Text.RegularExpressions.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Memory.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Reflection.Primitives.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.7/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Collections.Concurrent.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Text.Json.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Private.Uri.dll
----------------------------------------
Toolbox.Xml.Settings
    Assembly Version: 1.0.11.0
    Win32 Version: 1.0.11
    CodeBase: file:///C:/Users/Bogdan/Desktop/Bogdan/9.%20Astrofotografie/SLOOH/Slooh-Explorer-Binary-1.1.40/output/Toolbox.Xml.Settings.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.7/System.Resources.Extensions.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Collections.NonGeneric.dll
----------------------------------------
Toolbox.Help
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5
    CodeBase: file:///C:/Users/Bogdan/Desktop/Bogdan/9.%20Astrofotografie/SLOOH/Slooh-Explorer-Binary-1.1.40/output/Toolbox.Help.dll
----------------------------------------
Toolbox.Xml.Serialization
    Assembly Version: 1.0.63.0
    Win32 Version: 1.0.63
    CodeBase: file:///C:/Users/Bogdan/Desktop/Bogdan/9.%20Astrofotografie/SLOOH/Slooh-Explorer-Binary-1.1.40/output/Toolbox.Xml.Serialization.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Xml.XDocument
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Xml.XDocument.dll
----------------------------------------
System.Private.Xml.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Private.Xml.Linq.dll
----------------------------------------
System.Security.Cryptography.Csp
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Security.Cryptography.Csp.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Private.Xml.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.722.32203
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.7/System.Drawing.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Runtime.Intrinsics.dll
----------------------------------------
System.Net.Http.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Net.Http.Json.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.722.32202
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.7/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

**Comment by Bogdanel23** [comment]
The app is running under my user name in Task Manager.
The .xml file is present and shows the path to the folder correctly.
The path is the same i used in the last years so i don't know why the error shows up...

**Comment by Calteo** [comment]
Seems it is downloading already, but that only happens if you press the download button not at program startup.

Also you might want to set the other values if you want to download the parts. My settings are
![grafik](https://github.com/Calteo/Slooh.Explorer/assets/42947023/5a7b835a-b604-4ebb-b7a9-4fe5809b7d38)

**Comment by Bogdanel23** [comment]
update: if i delete the .xml file it resets the settings and now i can donwload to the specified path... weird

**Comment by Calteo** [comment]
Thats's stange, but if this is working right now for you again then this is good to know.
I will see if I somehow can reproduce the behavoir.

**Comment by Bogdanel23** [comment]
ok, thanks for the hints. consider this solved :)
